player-info-forwarding-mode = "modern"
forwarding-secret = "${VELOCITY_FORWARDING_SECRET}"

[servers]
lobby = "mc-lobby:25565"
example = "mc-example:25565"

[forced-hosts]
"lobby.oriom.dev" = ["lobby"]
"example.oriom.dev" = ["example"]
