FROM docker.io/library/node:18-alpine AS builder
WORKDIR /app

# package.json等をコピーして依存関係をインストール
COPY package*.json ./
RUN npm ci

# ソースコードをコピーしてビルド（TypeScript等の場合）
COPY . .
# RUN npm run build

FROM docker.io/library/node:18-alpine AS runner
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/index.js ./
# 必要な成果物をすべてコピー

# アプリケーションの待機ポート
EXPOSE 8080

CMD ["node", "index.js"]
