{ config, pkgs, lib, ... }:

{
  home.packages = with pkgs; [ git podman passt sops age ];

  home.sessionVariables.DOCKER_HOST = "unix:///run/user/$(id -u)/podman/podman.sock";

  xdg.configFile."containers/containers.conf".text = ''
    [network]
    default_rootless_network_cmd = "pasta"
  '';

  xdg.configFile."containers/policy.json".text = ''
    { "default": [{"type": "insecureAcceptAnything"}], "transports": {"docker-daemon": {"": [{"type":"insecureAcceptAnything"}]}} }
  '';

  xdg.configFile."containers/registries.conf".text = ''
    unqualified-search-registries = ["docker.io"]
  '';

  home.activation.startPodmanServices = lib.hm.dag.entryAfter ["writeBoundary"] ''
    PATH="${pkgs.systemd}/bin:${pkgs.podman}/bin:$PATH"
    
    echo "Running Podman Quadlet generator manually..."
    GEN_DIR="$HOME/.config/systemd/user"
    mkdir -p "$GEN_DIR"
    
    for f in "$GEN_DIR"/*.service "$GEN_DIR"/*.network "$GEN_DIR"/*.volume; do
      if [ -f "$f" ] && grep -q "Generated by Podman" "$f"; then
        rm -f "$f"
      fi
    done
    
    $DRY_RUN_CMD ${pkgs.podman}/lib/systemd/user-generators/podman-user-generator "$GEN_DIR" "$GEN_DIR" "$GEN_DIR"
    
    echo "Reloading systemd daemon..."
    $DRY_RUN_CMD systemctl --user daemon-reload
    
    echo "Restarting container services (Rolling update)..."
    ${if builtins.length config.podman.activeServices > 0 then ''
      $DRY_RUN_CMD systemctl --user restart ${builtins.concatStringsSep ".service " config.podman.activeServices}.service || true
    '' else ''
      echo "No services to start."
    ''}
  '';
}
