{ config, pkgs, lib, ... }:

let
  helper = import ../../lib/quadlet-helper.nix { inherit config pkgs lib; };

  # 稼働させるコンテナモジュールのリスト（ディレクトリ名のみを列挙）
  activeModules = [
    "cluster-network"
    "headscale"
    "caddy"
    "hello-world"
    "jpost-api"
    "mc-velocity"
  ];
in
{
  imports = [
    ../../lib/podman-options.nix
  ] ++ map (name: ../../containers/${name}/default.nix) activeModules;

  # --- これより下はホストシステム固有の最小設定 ---
  home.username = "ubuntu";
  home.homeDirectory = "/home/ubuntu";
  home.stateVersion = "23.11";

  home.packages = with pkgs; [ git podman passt sops age ];

  # SOPSのグローバル設定（鍵のパス等）
  sops.age.keyFile = "${config.home.homeDirectory}/.config/sops/age/keys.txt";

  home.sessionVariables.DOCKER_HOST = "unix:///run/user/$(id -u)/podman/podman.sock";
  xdg.configFile."containers/containers.conf".text = ''
    [network]
    default_rootless_network_cmd = "pasta"
  '';

  xdg.configFile."containers/policy.json".text = ''
    {
      "default": [
        {
          "type": "insecureAcceptAnything"
        }
      ],
      "transports": {
        "docker-daemon": {
          "": [{"type":"insecureAcceptAnything"}]
        }
      }
    }
  '';

  home.activation.startPodmanServices = lib.hm.dag.entryAfter ["writeBoundary"] ''
    PATH="${pkgs.systemd}/bin:${pkgs.podman}/bin:$PATH"
    
    echo "Running Podman Quadlet generator manually..."
    GEN_DIR="$HOME/.config/systemd/user"
    mkdir -p "$GEN_DIR"
    
    # 削除されたQuadletの古いサービスが残って競合しないよう、Podmanが過去に生成したファイルを事前にクリーンアップ
    for f in "$GEN_DIR"/*.service "$GEN_DIR"/*.network "$GEN_DIR"/*.volume; do
      if [ -f "$f" ] && grep -q "Generated by Podman" "$f"; then
        rm -f "$f"
      fi
    done
    
    # ジェネレーターに読み込み・書き込み先を指示して直接実行 (.container から .service が生成される)
    $DRY_RUN_CMD ${pkgs.podman}/lib/systemd/user-generators/podman-user-generator "$GEN_DIR" "$GEN_DIR" "$GEN_DIR"
    
    echo "Reloading systemd daemon..."
    $DRY_RUN_CMD systemctl --user daemon-reload
    
    echo "Starting container services..."
    ${if builtins.length config.podman.activeServices > 0 then ''
      $DRY_RUN_CMD systemctl --user start ${builtins.concatStringsSep ".service " config.podman.activeServices}.service || true
    '' else ''
      echo "No services to start."
    ''}
  '';
}
